// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krpmduhjqpbrzcqqkxcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtycG1kdWhqcXBicnpjcXFreGN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MDYyMzQsImV4cCI6MjA2MTQ4MjIzNH0.p5rwyiyr8hTqg3t-0yBYMxpsAcU-HhkQXJRW6Cj6ilY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);